In [1]:
# ============================================================
# LANGKAH 1: Import Library & Setup
# ============================================================
import sys
import os
import time
import json
import pandas as pd
from datetime import datetime

# Tambahkan parent folder ke path agar bisa import module Multi Agent
sys.path.insert(0, os.path.abspath('..'))

from agents.profile_agent import run as profile_run
from state import GameState

print("Semua library berhasil diimport!")
print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

Semua library berhasil diimport!
Timestamp: 2026-09-04 11:42:00

In [2]:
# ============================================================
# LANGKAH 2: Definisikan Variasi Usia & Gender
# ============================================================
# 3 kategori usia × 2 gender = 6 variasi profil NPC

USIA_LIST = ["remaja", "dewasa", "orang tua"]
GENDER_LIST = ["pria", "wanita"]
JUMLAH_ITERASI = 5  # Berapa kali setiap variasi dipanggil

variasi_list = []
for usia in USIA_LIST:
    for gender in GENDER_LIST:
        variasi_list.append((usia, gender))

print(f"Total variasi: {len(variasi_list)} (3 usia × 2 gender)")
print(f"Iterasi per variasi: {JUMLAH_ITERASI}")
print(f"Total panggilan profile agent: {len(variasi_list) * JUMLAH_ITERASI}")
print(f"\nDaftar variasi:")
for i, (u, g) in enumerate(variasi_list, 1):
    print(f"  {i}. usia={u}, gender={g}")

Total variasi: 6 (3 usia × 2 gender)
Iterasi per variasi: 5
Total panggilan profile agent: 30

Daftar variasi:
  1. usia=remaja, gender=pria
  2. usia=remaja, gender=wanita
  3. usia=dewasa, gender=pria
  4. usia=dewasa, gender=wanita
  5. usia=orang tua, gender=pria
  6. usia=orang tua, gender=wanita

In [3]:
# ============================================================
# LANGKAH 3: Jalankan Profile Agent & Ukur Waktu
# ============================================================
# Setiap panggilan profile_agent.run() akan diukur waktunya
# menggunakan time.perf_counter() untuk presisi tinggi.

hasil_semua = []
total_panggilan = len(variasi_list) * JUMLAH_ITERASI
panggilan_ke = 0

for usia, gender in variasi_list:
    for iterasi in range(1, JUMLAH_ITERASI + 1):
        panggilan_ke += 1
        
        # Buat state input untuk profile agent
        state: GameState = {
            "usia": usia,
            "gender": gender,
        }
        
        # Catat waktu mulai
        t_start = time.perf_counter()
        
        # Panggil profile agent
        result = profile_run(state)
        
        # Catat waktu selesai
        t_end = time.perf_counter()
        waktu_detik = round(t_end - t_start, 3)
        
        # Simpan hasil
        hasil_semua.append({
            "usia": usia,
            "gender": gender,
            "iterasi": iterasi,
            "nama": result.get("nama", ""),
            "background": result.get("background", ""),
            "masalah_hari_ini": result.get("masalah_hari_ini", ""),
            "ocean_openness": result["ocean"]["openness"],
            "ocean_conscientiousness": result["ocean"]["conscientiousness"],
            "ocean_extraversion": result["ocean"]["extraversion"],
            "ocean_agreeableness": result["ocean"]["agreeableness"],
            "ocean_neuroticism": result["ocean"]["neuroticism"],
            "max_fails": result.get("max_fails", 0),
            "estimasi_waktu_detik": waktu_detik,
        })
        
        print(f"[{panggilan_ke}/{total_panggilan}] usia={usia}, gender={gender}, "
              f"iterasi={iterasi} → {result.get('nama', '?')} "
              f"({waktu_detik}s)")

print(f"\n✅ Selesai! Total {len(hasil_semua)} profile berhasil digenerate.")

  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[1/30] usia=remaja, gender=pria, iterasi=1 → Zaki (7.972s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[2/30] usia=remaja, gender=pria, iterasi=2 → Iwan (5.515s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[3/30] usia=remaja, gender=pria, iterasi=3 → Pandu (5.926s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[4/30] usia=remaja, gender=pria, iterasi=4 → Candra (4.992s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[5/30] usia=remaja, gender=pria, iterasi=5 → Oscar (4.795s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[6/30] usia=remaja, gender=wanita, iterasi=1 → Ulya (6.295s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[7/30] usia=remaja, gender=wanita, iterasi=2 → Bella (8.077s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[8/30] usia=remaja, gender=wanita, iterasi=3 → Zahra (6.368s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[9/30] usia=remaja, gender=wanita, iterasi=4 → Lala (5.862s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[10/30] usia=remaja, gender=wanita, iterasi=5 → Elsa (5.573s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[11/30] usia=dewasa, gender=pria, iterasi=1 → Lukman (4.251s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[12/30] usia=dewasa, gender=pria, iterasi=2 → Yoga (5.379s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[13/30] usia=dewasa, gender=pria, iterasi=3 → Bayu (6.604s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[14/30] usia=dewasa, gender=pria, iterasi=4 → Pandu (6.256s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[15/30] usia=dewasa, gender=pria, iterasi=5 → Ilham (4.704s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[16/30] usia=dewasa, gender=wanita, iterasi=1 → Vina (4.813s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[17/30] usia=dewasa, gender=wanita, iterasi=2 → Amelia (4.839s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[18/30] usia=dewasa, gender=wanita, iterasi=3 → Wati (4.561s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[19/30] usia=dewasa, gender=wanita, iterasi=4 → Yuni (6.611s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[20/30] usia=dewasa, gender=wanita, iterasi=5 → Era (6.021s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[21/30] usia=orang tua, gender=pria, iterasi=1 → Hadi (5.702s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[22/30] usia=orang tua, gender=pria, iterasi=2 → Gunawan (5.961s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[23/30] usia=orang tua, gender=pria, iterasi=3 → Lukman (5.931s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[24/30] usia=orang tua, gender=pria, iterasi=4 → Candra (6.372s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[25/30] usia=orang tua, gender=pria, iterasi=5 → Galih (8.307s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[26/30] usia=orang tua, gender=wanita, iterasi=1 → Anya (6.1s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[27/30] usia=orang tua, gender=wanita, iterasi=2 → Diana (6.816s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[28/30] usia=orang tua, gender=wanita, iterasi=3 → Diana (7.995s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[29/30] usia=orang tua, gender=wanita, iterasi=4 → Era (7.432s)
  [LLM INFO] Model 'GPT-5.6-luna' adalah reasoning model — parameter sampling (temperature/frequency_penalty/presence_penalty) di-skip.
[30/30] usia=orang tua, gender=wanita, iterasi=5 → Lala (9.649s)

✅ Selesai! Total 30 profile berhasil digenerate.

In [4]:
# ============================================================
# LANGKAH 4: Buat DataFrame & Tampilkan Data
# ============================================================
df = pd.DataFrame(hasil_semua)

# Urutkan kolom agar rapi
kolom_urutan = [
    "usia", "gender", "iterasi", "nama",
    "ocean_openness", "ocean_conscientiousness", "ocean_extraversion",
    "ocean_agreeableness", "ocean_neuroticism",
    "max_fails", "estimasi_waktu_detik",
    "background", "masalah_hari_ini"
]
df = df[kolom_urutan]

print(f"Total data: {len(df)} baris")
print(f"Kolom: {list(df.columns)}")
print(f"\nTipe data:")
print(df.dtypes)
print(f"\n10 data pertama:")
df.head(10)

Total data: 30 baris
Kolom: ['usia', 'gender', 'iterasi', 'nama', 'ocean_openness', 'ocean_conscientiousness', 'ocean_extraversion', 'ocean_agreeableness', 'ocean_neuroticism', 'max_fails', 'estimasi_waktu_detik', 'background', 'masalah_hari_ini']

Tipe data:
usia                           str
gender                         str
iterasi                      int64
nama                           str
ocean_openness               int64
ocean_conscientiousness      int64
ocean_extraversion           int64
ocean_agreeableness          int64
ocean_neuroticism            int64
max_fails                    int64
estimasi_waktu_detik       float64
background                     str
masalah_hari_ini               str
dtype: object

10 data pertama:

,usia,gender,iterasi,nama,ocean_openness,ocean_conscientiousness,ocean_extraversion,ocean_agreeableness,ocean_neuroticism,max_fails,estimasi_waktu_detik,background,masalah_hari_ini
0,remaja,pria,1,Zaki,48,67,28,54,64,2,7.972,Mahasiswa semester awal yang tiap hari kuliah ...,Laporan praktikum pemrograman tentang analisis...
1,remaja,pria,2,Iwan,61,54,91,88,42,3,5.515,Siswa SMA yang tiap hari pulang sekolah langsu...,Iwan harus memilih antara ikut seleksi futsal ...
2,remaja,pria,3,Pandu,64,43,55,68,79,2,5.926,Mahasiswa semester awal yang tiap hari kuliah ...,Tugas presentasi mata kuliah Komunikasi yang h...
3,remaja,pria,4,Candra,38,72,82,78,68,2,4.992,Siswa SMA yang tiap hari pulang-pergi sekolah ...,Besok pagi dia harus mengikuti tes seleksi bea...
4,remaja,pria,5,Oscar,54,67,46,43,72,2,4.795,Pelajar SMA yang setiap hari berangkat sekolah...,Pacarnya mengakhiri hubungan lewat chat setela...
5,remaja,wanita,1,Ulya,52,72,24,69,66,2,6.295,Siswi SMA yang setiap hari berangkat sekolah n...,Dompetnya cuma berisi dua ribu rupiah karena u...
6,remaja,wanita,2,Bella,54,43,64,57,84,2,8.077,"Siswi SMA yang tiap hari sekolah, membantu jua...",Iuran kostum pentas seni sebesar Rp85.000 haru...
7,remaja,wanita,3,Zahra,64,35,88,66,82,2,6.368,Siswi SMA yang tiap hari pulang sekolah sambil...,"Dompetnya tinggal dua ribu rupiah, sementara i..."
8,remaja,wanita,4,Lala,68,48,91,88,32,3,5.862,Siswi SMA yang setiap hari aktif di OSIS dan s...,"Saat latihan presentasi acara sekolah, seorang..."
9,remaja,wanita,5,Elsa,88,67,24,38,78,1,5.573,"Siswi SMA yang tiap hari belajar, mengerjakan ...",Dompetnya benar-benar kosong setelah uang jaja...

In [5]:
# ============================================================
# LANGKAH 5: Statistik Estimasi Waktu per Kategori
# ============================================================
print("=" * 70)
print("STATISTIK ESTIMASI WAKTU PER KATEGORI (USIA + GENDER)")
print("=" * 70)

summary_kategori = df.groupby(["usia", "gender"]).agg(
    jumlah=("estimasi_waktu_detik", "count"),
    rata_rata_detik=("estimasi_waktu_detik", "mean"),
    std_detik=("estimasi_waktu_detik", "std"),
    min_detik=("estimasi_waktu_detik", "min"),
    max_detik=("estimasi_waktu_detik", "max"),
    median_detik=("estimasi_waktu_detik", "median"),
).round(3)

print(summary_kategori)
print()

# Rata-rata per kategori dalam bentuk tabel pivot
print("=" * 70)
print("RATA-RATA WAKTU (detik) — PIVOT TABLE")
print("=" * 70)
pivot_mean = df.pivot_table(
    values="estimasi_waktu_detik",
    index="usia",
    columns="gender",
    aggfunc="mean"
).round(3)
print(pivot_mean)

======================================================================
STATISTIK ESTIMASI WAKTU PER KATEGORI (USIA + GENDER)
======================================================================
                  jumlah  rata_rata_detik  std_detik  min_detik  max_detik  \
usia      gender
dewasa    pria         5            5.439      0.997      4.251      6.604
          wanita       5            5.369      0.896      4.561      6.611
orang tua pria         5            6.455      1.063      5.702      8.307
          wanita       5            7.598      1.346      6.100      9.649
remaja    pria         5            5.840      1.272      4.795      7.972
          wanita       5            6.435      0.974      5.573      8.077

                  median_detik
usia      gender
dewasa    pria           5.379
          wanita         4.839
orang tua pria           5.961
          wanita         7.432
remaja    pria           5.515
          wanita         6.295

======================================================================
RATA-RATA WAKTU (detik) — PIVOT TABLE
======================================================================
gender      pria  wanita
usia
dewasa     5.439   5.369
orang tua  6.455   7.598
remaja     5.840   6.435

In [6]:
# ============================================================
# LANGKAH 6: Statistik Estimasi Waktu per Usia & per Gender
# ============================================================

print("=" * 70)
print("RATA-RATA WAKTU PER USIA")
print("=" * 70)
summary_usia = df.groupby("usia").agg(
    jumlah=("estimasi_waktu_detik", "count"),
    rata_rata_detik=("estimasi_waktu_detik", "mean"),
    std_detik=("estimasi_waktu_detik", "std"),
    min_detik=("estimasi_waktu_detik", "min"),
    max_detik=("estimasi_waktu_detik", "max"),
).round(3)
print(summary_usia)

print("\n" + "=" * 70)
print("RATA-RATA WAKTU PER GENDER")
print("=" * 70)
summary_gender = df.groupby("gender").agg(
    jumlah=("estimasi_waktu_detik", "count"),
    rata_rata_detik=("estimasi_waktu_detik", "mean"),
    std_detik=("estimasi_waktu_detik", "std"),
    min_detik=("estimasi_waktu_detik", "min"),
    max_detik=("estimasi_waktu_detik", "max"),
).round(3)
print(summary_gender)

======================================================================
RATA-RATA WAKTU PER USIA
======================================================================
           jumlah  rata_rata_detik  std_detik  min_detik  max_detik
usia
dewasa         10            5.404      0.895      4.251      6.611
orang tua      10            7.026      1.293      5.702      9.649
remaja         10            6.138      1.113      4.795      8.077

======================================================================
RATA-RATA WAKTU PER GENDER
======================================================================
        jumlah  rata_rata_detik  std_detik  min_detik  max_detik
gender
pria        15            5.911      1.121      4.251      8.307
wanita      15            6.467      1.381      4.561      9.649

In [7]:
# ============================================================
# LANGKAH 7: Tabel Lengkap (Semua Hasil)
# ============================================================
# Tampilkan semua data tanpa kolom background & masalah (terlalu panjang)
kolom_tampil = [c for c in df.columns if c not in ["background", "masalah_hari_ini"]]
print(f"Menampilkan {len(df)} baris data:")
print("-" * 100)
df[kolom_tampil]

Menampilkan 30 baris data:
----------------------------------------------------------------------------------------------------

,usia,gender,iterasi,nama,ocean_openness,ocean_conscientiousness,ocean_extraversion,ocean_agreeableness,ocean_neuroticism,max_fails,estimasi_waktu_detik
0,remaja,pria,1,Zaki,48,67,28,54,64,2,7.972
1,remaja,pria,2,Iwan,61,54,91,88,42,3,5.515
2,remaja,pria,3,Pandu,64,43,55,68,79,2,5.926
3,remaja,pria,4,Candra,38,72,82,78,68,2,4.992
4,remaja,pria,5,Oscar,54,67,46,43,72,2,4.795
5,remaja,wanita,1,Ulya,52,72,24,69,66,2,6.295
6,remaja,wanita,2,Bella,54,43,64,57,84,2,8.077
7,remaja,wanita,3,Zahra,64,35,88,66,82,2,6.368
8,remaja,wanita,4,Lala,68,48,91,88,32,3,5.862
9,remaja,wanita,5,Elsa,88,67,24,38,78,1,5.573
10,dewasa,pria,1,Lukman,36,78,27,58,48,2,4.251
11,dewasa,pria,2,Yoga,88,58,86,88,48,3,5.379
12,dewasa,pria,3,Bayu,38,82,42,64,58,2,6.604
13,dewasa,pria,4,Pandu,64,48,28,67,82,2,6.256
14,dewasa,pria,5,Ilham,76,84,24,68,74,2,4.704
15,dewasa,wanita,1,Vina,34,78,24,52,89,2,4.813
16,dewasa,wanita,2,Amelia,68,52,88,57,93,2,4.839
17,dewasa,wanita,3,Wati,58,72,24,68,91,2,4.561
18,dewasa,wanita,4,Yuni,93,64,78,88,49,3,6.611
19,dewasa,wanita,5,Era,68,86,24,73,84,2,6.021
20,orang tua,pria,1,Hadi,64,68,74,91,88,2,5.702
21,orang tua,pria,2,Gunawan,78,82,43,81,68,2,5.961
22,orang tua,pria,3,Lukman,84,78,46,58,22,3,5.931
23,orang tua,pria,4,Candra,91,68,76,92,84,2,6.372
24,orang tua,pria,5,Galih,68,76,58,91,42,3,8.307
25,orang tua,wanita,1,Anya,91,68,76,94,83,2,6.100
26,orang tua,wanita,2,Diana,88,52,78,72,42,3,6.816
27,orang tua,wanita,3,Diana,88,65,78,58,84,2,7.995
28,orang tua,wanita,4,Era,72,84,27,93,86,2,7.432
29,orang tua,wanita,5,Lala,46,63,48,74,82,2,9.649

In [8]:
# ============================================================
# LANGKAH 8: Simpan Hasil ke CSV
# ============================================================
output_path = "hasil_profile_timing.csv"
df.to_csv(output_path, index=False, encoding="utf-8")
print(f"✅ Hasil disimpan ke: {output_path}")
print(f"   Jumlah baris: {len(df)}")
print(f"   Jumlah kolom: {len(df.columns)}")
print(f"\nStatistik global estimasi waktu:")
print(f"   Rata-rata : {df['estimasi_waktu_detik'].mean():.3f} detik")
print(f"   Std dev   : {df['estimasi_waktu_detik'].std():.3f} detik")
print(f"   Min       : {df['estimasi_waktu_detik'].min():.3f} detik")
print(f"   Max       : {df['estimasi_waktu_detik'].max():.3f} detik")
print(f"   Median    : {df['estimasi_waktu_detik'].median():.3f} detik")

✅ Hasil disimpan ke: hasil_profile_timing.csv
   Jumlah baris: 30
   Jumlah kolom: 13

Statistik global estimasi waktu:
   Rata-rata : 6.189 detik
   Std dev   : 1.268 detik
   Min       : 4.251 detik
   Max       : 9.649 detik
   Median    : 5.991 detik